import { Product } from './types';

export const mockProducts: Product[] = [
  {
    id: 'p1',
    name: 'Nordic Oak Chair',
    description: 'A beautifully designed minimalist chair perfect for any modern home. Made from sustainably sourced oak and featuring a comfortable ergonomic curved back.',
    price: 240.00,
    imageUrl: 'https://images.unsplash.com/photo-1592078615290-033ee584e267?w=500&q=80',
    category: 'Furniture',
    inStock: true,
  },
  {
    id: 'p2',
    name: 'Matte Pendant Lamp',
    description: 'Add a warm glow to your living space with this handcrafted ceramic table lamp. Features a textured matte finish and a linen shade.',
    price: 185.00,
    imageUrl: 'https://images.unsplash.com/photo-1507473885765-e6ed057f782c?w=500&q=80',
    category: 'Lighting',
    inStock: true,
  },
  {
    id: 'p3',
    name: 'Ceramic Sculpt Vase',
    description: 'Set of three hand-blown glass vases in varying heights and muted tones. Ideal for displaying fresh or dried floral arrangements.',
    price: 72.00,
    imageUrl: 'https://images.unsplash.com/photo-1581783342308-f792dbdd27c5?w=500&q=80',
    category: 'Decor',
    inStock: true,
  },
  {
    id: 'p4',
    name: 'Linen Throw Pillow',
    description: 'Cozy up with this ultra-soft, 100% linen throw pillow. Features a classic minimal pattern.',
    price: 45.00,
    imageUrl: 'https://images.unsplash.com/photo-1580661869408-55ab23f2ca6e?w=500&q=80',
    category: 'Textiles',
    inStock: false,
  },
  {
    id: 'p5',
    name: 'Walnut Wall Shelf',
    description: 'Solid walnut shelf with clean lines and a durable finish. A timeless piece that anchors your living room.',
    price: 110.00,
    imageUrl: 'https://images.unsplash.com/photo-1532372320572-cda25653a26d?w=500&q=80',
    category: 'Furniture',
    inStock: true,
  },
  {
    id: 'p6',
    name: 'Concrete Desk Clock',
    description: 'A striking minimalist clock featuring bold geometric shapes and neutral tones. Perfect for adding a contemporary touch.',
    price: 55.00,
    imageUrl: 'https://images.unsplash.com/photo-1513519245088-0e12902e5a38?w=500&q=80',
    category: 'Decor',
    inStock: true,
  },
  {
    id: 'p7',
    name: 'Woven Floor Rug',
    description: 'Hand-woven natural fiber rug offering durability and texture to any space.',
    price: 320.00,
    imageUrl: 'https://images.unsplash.com/photo-1579603099951-4d37532f81d1?w=500&q=80',
    category: 'Textiles',
    inStock: true,
  },
  {
    id: 'p8',
    name: 'Minimalist Floor Lamp',
    description: 'Sleek metal floor lamp with adjustable head and matte black finish.',
    price: 155.00,
    imageUrl: 'https://images.unsplash.com/photo-1513506003901-1e6a229e2d15?w=500&q=80',
    category: 'Lighting',
    inStock: true,
  },
  {
    id: 'p9',
    name: 'Lounge Sofa',
    description: 'Deep-seated lounge sofa upholstered in premium boucle fabric.',
    price: 1250.00,
    imageUrl: 'https://images.unsplash.com/photo-1493663284031-b7e3aefcae8e?w=500&q=80',
    category: 'Furniture',
    inStock: true,
  }
];
